#!/bin/bash -uxe

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

git -C $DIR submodule init
git -C $DIR submodule update

make -C $DIR/julia -j$(nproc) \
    LLVM_ASSERTIONS=1 \
    FORCE_ASSERTIONS=1
