#!/usr/bin/env bash
set -ue

# script to prepare the environment and launch julia

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR"/activate

julia -O0 --compiled-modules=no -t1 --startup-file=no "$@"
