#!/usr/bin/env bash
set -ue

# script to prepare and start the testcase reduction process

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"

rm -rf src
rm -f src.lst

# creduce works with flat files, and doesn't respect directories.
#
# to overcome this, we first discover which files to reduce,
# write them to a flat directory (src) and save the paths to a file (src.lst).
#
# during execution, we'll use that file to recover the original file hierarchy.

SOURCES=(main.jl)
while IFS= read -r -d $'\0'; do
    SOURCES+=("$REPLY")
done < <(find depot/packages -type f -name "*.jl" -print0)

i=1
mkdir src
echo "Reducing the following sources:"
for path in "${SOURCES[@]}"; do
    echo "- $path"
    echo "$path" >> src.lst
    ln -s "../$path" "src/$i.jl"
    (( i++ ))
done

chmod +w src/*
nice -n 20 creduce --tidy --n $(nproc) --not-c ./run src/*
