#!/usr/bin/env bash
set -ue

# script to prepare the environment and execute the main.jl script

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR"/activate

julia main.jl |& grep "Segmentation fault"
